### ISSUE TITLE
[BUG] WSL 소켓 닫힘 문제

### ISSUE THREAD

**Issue by airmang** [bareun-nlp/bareun-support#6]
**버그에 대한 설명**
WSL 환경에서 파이썬을 이용해 Tagger 호출 시 소켓이 닫힙니다.
프로세스 실행 중이고 PORT:5656도 LISTEN 상태입니다.

추측으로는 gRPC 연결 시간 제한 10초를 넘겨 소켓이 닫힌것일수도 있다고 생각합니다.

**버그 발생 재현**
실행한 py 코드 

tagger = Tagger(API_KEY, 'localhost',5656)

class morph:
    def __init__(self, sentence):
        self.sentence = sentence

    def termination(cls):
        termination_keys = {'EP', 'EF', 'EC', 'ETN', 'ETM'}
        result = tagger.tags([cls.sentence])
        morph_list = result.pos()
        filtered = [t for t in morph_list if t[1] in termination_keys]
        print(filtered)
        return filtered

S1 = morph('봄이오면 벚꽃을 보러가요.')
S1.termination()

**예상 결과**
기대하는 결과에 대한 명확하고 간결한 설명을 부탁드립니다.

**화면 스크린샷**

Traceback (most recent call last):
  File "/home/airman/Bareun_Linux/morph.py", line 23, in <module>
    S1.termination()
  File "/home/airman/Bareun_Linux/morph.py", line 16, in termination
    result = tagger.tags([cls.sentence])
  File "/home/airman/.local/lib/python3.8/site-packages/bareunpy/_tagger.py", line 229, in tags
    raise e
  File "/home/airman/.local/lib/python3.8/site-packages/bareunpy/_tagger.py", line 226, in tags
    res = self.client.analyze_syntax(p, self.domain, auto_split=False)
  File "/home/airman/.local/lib/python3.8/site-packages/bareunpy/_lang_service_client.py", line 64, in analyze_syntax
    raise e
  File "/home/airman/.local/lib/python3.8/site-packages/bareunpy/_lang_service_client.py", line 60, in analyze_syntax
    res, c = self.stub.AnalyzeSyntax.with_call(
  File "/home/airman/.local/lib/python3.8/site-packages/grpc/_channel.py", line 957, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/home/airman/.local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:5656 {grpc_message:"Socket closed", grpc_status:14, created_time:"2023-03-25T01:46:00.577856549+09:00"}"

**데스크탑 (다음의 정보를 입력해주세요.):**
 - OS: [WSL/ Ubuntu 22.10]
 - Browser, Language [ chrome, python]
 - Version [예시 22, 3.7]

**Comment by airmang** [comment]
새로운 환경에서 WSL 설치 후 실행 결과 정상적으로 작동되는걸 확인했습니다.

이전의 환경과 차이가 있다면, 윈도우용 바른 서버 설치 유무인것 같습니다.
윈도우 바른서버 설치 후 WSL 바른서버와 충돌이 있는게 아닌가 합니다.

**Comment by gih2yun** [comment]
네, 동작 확인해주셔서 감사합니다.

**Comment by gih2yun** [comment]
@airmang 윈도우 서버를 삭제하려면, 윈도우 설치를 삭제하면 서비스를 중지하고, 삭제됩니다.
만일 서비스 중지가 잘 되지 않는다면, 서비스 중지를 시킨 다음에 삭제하면 좋을 것 같습니다.

서비스를 중지시키려면, 
- Win-R 키를 눌러서, services.msc를 실행하면 서비스 관리자 화면이 나옵니다. 여기에서 중지하실 수 있습니다.
- 관리자 권한으로 실행한 명령창에서  `sc stop bareunsvc`를 실행하시고, `sc delete bareunsvc`  하시면 됩니다. 

삭제해도 서비스가 동작하고 있는지 다시한번 확인해주시면 고맙겠습니다.
